#52 refactor tasks
rizinorg/rz-hexagon pull request #63
Opened 2022-04-24 07:57 UTC by Rot127

This PR ticks most boxes in https://github.com/rizinorg/rz-hexagon/issues/52.

Namely:

- [x] Fix grammar/spelling issues (`handwritten` -> `hand-written`)
- [x] Move the foloowing pattern in its own function
  ```python
  with open("handwritten/hexagon_il_h/include.h") as include:
    set_pos_after_license(include)
    code += "".join(include.readlines())
  ```
- [x] Move the following pattern in its own function:
  ```python
  if compare_src_to_old_src(code, path):
     self.unchanged_files.append(path)
     return
  with open(path, "w+") as dest:
     dest.writelines(code)
     log("analysis_hexagon.c written to {}".format(path), LogLevel.INFO)
   ```
- [x] Replaced `"..".format()` patterns with `f"..."` formatting in https://github.com/rizinorg/rz-hexagon/pull/60 
- [x] Refactor `parse_instruction()`
  The method for parsing a Duplex or normal instruction are almost the same.
  The method should be in `InstructionTemplate` from which `DuplexInstruction` and `Instruction` inherit.
  
  Methods in question:
  https://github.com/rizinorg/rz-hexagon/blob/7df09f53826546b8e0a328021813882e13e21de1/DuplexInstruction.py#L99
  https://github.com/rizinorg/rz-hexagon/blob/7df09f53826546b8e0a328021813882e13e21de1/Instruction.py#L106

- [x] Update license date
- [x] Remove or include out-commented code (mostly logs)

2022-04-24 12:33 UTC, XVilka approved these changes

2022-04-24 12:33 UTC, XVilka commented on README.md
> +- As a developer you also need `black, flake8, reuse`.
`black`, `flake8`, `reuse`

2022-04-24 12:33 UTC, XVilka commented on README.md
> +**Before you open a PR please run: `black -l 120 *.py && flake8 --max-line-length=120 && reuse lint`** and fix the warnings.
Are those in CI as well?

2022-04-24 12:42 UTC, thestr4ng3r requested changes
"handwritten" is the correct form: https://dictionary.cambridge.org/de/worterbuch/englisch/handwritten

2022-04-25 08:52 UTC, Rot127 commented on README.md
> +**Before you open a PR please run: `black -l 120 *.py && flake8 --max-line-length=120 && reuse lint`** and fix the warnings.
Not yet.

2022-04-26 05:17 UTC, thestr4ng3r approved these changes

2022-04-26 11:39 UTC, merged